// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geocoder.proto

package geocoder

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Location struct {
	Provider             string            `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	FormattedAddress     string            `protobuf:"bytes,2,opt,name=formatted_address,json=formattedAddress,proto3" json:"formatted_address,omitempty"`
	StreetNumber         string            `protobuf:"bytes,4,opt,name=street_number,json=streetNumber,proto3" json:"street_number,omitempty"`
	StreetName           string            `protobuf:"bytes,5,opt,name=street_name,json=streetName,proto3" json:"street_name,omitempty"`
	Locality             string            `protobuf:"bytes,6,opt,name=locality,proto3" json:"locality,omitempty"`
	Sublocality          string            `protobuf:"bytes,7,opt,name=sublocality,proto3" json:"sublocality,omitempty"`
	Timezone             string            `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	PostalCode           string            `protobuf:"bytes,9,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Id                   string            `protobuf:"bytes,20,opt,name=id,proto3" json:"id,omitempty"`
	Country              *Country          `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	State                *State            `protobuf:"bytes,12,opt,name=state,proto3" json:"state,omitempty"`
	LatLng               *LatLng           `protobuf:"bytes,10,opt,name=latLng,proto3" json:"latLng,omitempty"`
	Bounds               *Bounds           `protobuf:"bytes,13,opt,name=bounds,proto3" json:"bounds,omitempty"`
	AdminLevels          []*AdminLevel     `protobuf:"bytes,11,rep,name=admin_levels,json=adminLevels,proto3" json:"admin_levels,omitempty"`
	Components           map[string]string `protobuf:"bytes,21,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0eb003880ea8c15, []int{0}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Location) GetFormattedAddress() string {
	if m != nil {
		return m.FormattedAddress
	}
	return ""
}

func (m *Location) GetStreetNumber() string {
	if m != nil {
		return m.StreetNumber
	}
	return ""
}

func (m *Location) GetStreetName() string {
	if m != nil {
		return m.StreetName
	}
	return ""
}

func (m *Location) GetLocality() string {
	if m != nil {
		return m.Locality
	}
	return ""
}

func (m *Location) GetSublocality() string {
	if m != nil {
		return m.Sublocality
	}
	return ""
}

func (m *Location) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Location) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Location) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Location) GetCountry() *Country {
	if m != nil {
		return m.Country
	}
	return nil
}

func (m *Location) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Location) GetLatLng() *LatLng {
	if m != nil {
		return m.LatLng
	}
	return nil
}

func (m *Location) GetBounds() *Bounds {
	if m != nil {
		return m.Bounds
	}
	return nil
}

func (m *Location) GetAdminLevels() []*AdminLevel {
	if m != nil {
		return m.AdminLevels
	}
	return nil
}

func (m *Location) GetComponents() map[string]string {
	if m != nil {
		return m.Components
	}
	return nil
}

type Bounds struct {
	NorthEast            *LatLng  `protobuf:"bytes,1,opt,name=northEast,proto3" json:"northEast,omitempty"`
	SouthWest            *LatLng  `protobuf:"bytes,2,opt,name=southWest,proto3" json:"southWest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bounds) Reset()         { *m = Bounds{} }
func (m *Bounds) String() string { return proto.CompactTextString(m) }
func (*Bounds) ProtoMessage()    {}
func (*Bounds) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0eb003880ea8c15, []int{1}
}

func (m *Bounds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bounds.Unmarshal(m, b)
}
func (m *Bounds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bounds.Marshal(b, m, deterministic)
}
func (m *Bounds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bounds.Merge(m, src)
}
func (m *Bounds) XXX_Size() int {
	return xxx_messageInfo_Bounds.Size(m)
}
func (m *Bounds) XXX_DiscardUnknown() {
	xxx_messageInfo_Bounds.DiscardUnknown(m)
}

var xxx_messageInfo_Bounds proto.InternalMessageInfo

func (m *Bounds) GetNorthEast() *LatLng {
	if m != nil {
		return m.NorthEast
	}
	return nil
}

func (m *Bounds) GetSouthWest() *LatLng {
	if m != nil {
		return m.SouthWest
	}
	return nil
}

type AdminLevel struct {
	Level                int32    `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminLevel) Reset()         { *m = AdminLevel{} }
func (m *AdminLevel) String() string { return proto.CompactTextString(m) }
func (*AdminLevel) ProtoMessage()    {}
func (*AdminLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0eb003880ea8c15, []int{2}
}

func (m *AdminLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminLevel.Unmarshal(m, b)
}
func (m *AdminLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminLevel.Marshal(b, m, deterministic)
}
func (m *AdminLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminLevel.Merge(m, src)
}
func (m *AdminLevel) XXX_Size() int {
	return xxx_messageInfo_AdminLevel.Size(m)
}
func (m *AdminLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminLevel.DiscardUnknown(m)
}

var xxx_messageInfo_AdminLevel proto.InternalMessageInfo

func (m *AdminLevel) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *AdminLevel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdminLevel) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Country struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Country) Reset()         { *m = Country{} }
func (m *Country) String() string { return proto.CompactTextString(m) }
func (*Country) ProtoMessage()    {}
func (*Country) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0eb003880ea8c15, []int{3}
}

func (m *Country) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Country.Unmarshal(m, b)
}
func (m *Country) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Country.Marshal(b, m, deterministic)
}
func (m *Country) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Country.Merge(m, src)
}
func (m *Country) XXX_Size() int {
	return xxx_messageInfo_Country.Size(m)
}
func (m *Country) XXX_DiscardUnknown() {
	xxx_messageInfo_Country.DiscardUnknown(m)
}

var xxx_messageInfo_Country proto.InternalMessageInfo

func (m *Country) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Country) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type State struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0eb003880ea8c15, []int{4}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *State) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type LatLng struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatLng) Reset()         { *m = LatLng{} }
func (m *LatLng) String() string { return proto.CompactTextString(m) }
func (*LatLng) ProtoMessage()    {}
func (*LatLng) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0eb003880ea8c15, []int{5}
}

func (m *LatLng) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatLng.Unmarshal(m, b)
}
func (m *LatLng) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatLng.Marshal(b, m, deterministic)
}
func (m *LatLng) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatLng.Merge(m, src)
}
func (m *LatLng) XXX_Size() int {
	return xxx_messageInfo_LatLng.Size(m)
}
func (m *LatLng) XXX_DiscardUnknown() {
	xxx_messageInfo_LatLng.DiscardUnknown(m)
}

var xxx_messageInfo_LatLng proto.InternalMessageInfo

func (m *LatLng) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *LatLng) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type Timezone struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timezone) Reset()         { *m = Timezone{} }
func (m *Timezone) String() string { return proto.CompactTextString(m) }
func (*Timezone) ProtoMessage()    {}
func (*Timezone) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0eb003880ea8c15, []int{6}
}

func (m *Timezone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timezone.Unmarshal(m, b)
}
func (m *Timezone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timezone.Marshal(b, m, deterministic)
}
func (m *Timezone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timezone.Merge(m, src)
}
func (m *Timezone) XXX_Size() int {
	return xxx_messageInfo_Timezone.Size(m)
}
func (m *Timezone) XXX_DiscardUnknown() {
	xxx_messageInfo_Timezone.DiscardUnknown(m)
}

var xxx_messageInfo_Timezone proto.InternalMessageInfo

func (m *Timezone) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type LocationRequest struct {
	Provider             string            `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Address              string            `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Latlng               *LatLng           `protobuf:"bytes,3,opt,name=latlng,proto3" json:"latlng,omitempty"`
	Query                map[string]string `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LocationRequest) Reset()         { *m = LocationRequest{} }
func (m *LocationRequest) String() string { return proto.CompactTextString(m) }
func (*LocationRequest) ProtoMessage()    {}
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0eb003880ea8c15, []int{7}
}

func (m *LocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationRequest.Unmarshal(m, b)
}
func (m *LocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationRequest.Marshal(b, m, deterministic)
}
func (m *LocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationRequest.Merge(m, src)
}
func (m *LocationRequest) XXX_Size() int {
	return xxx_messageInfo_LocationRequest.Size(m)
}
func (m *LocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LocationRequest proto.InternalMessageInfo

func (m *LocationRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *LocationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *LocationRequest) GetLatlng() *LatLng {
	if m != nil {
		return m.Latlng
	}
	return nil
}

func (m *LocationRequest) GetQuery() map[string]string {
	if m != nil {
		return m.Query
	}
	return nil
}

type LocationResponse struct {
	Locations            []*Location `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	Exists               bool        `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LocationResponse) Reset()         { *m = LocationResponse{} }
func (m *LocationResponse) String() string { return proto.CompactTextString(m) }
func (*LocationResponse) ProtoMessage()    {}
func (*LocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0eb003880ea8c15, []int{8}
}

func (m *LocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationResponse.Unmarshal(m, b)
}
func (m *LocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationResponse.Marshal(b, m, deterministic)
}
func (m *LocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationResponse.Merge(m, src)
}
func (m *LocationResponse) XXX_Size() int {
	return xxx_messageInfo_LocationResponse.Size(m)
}
func (m *LocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LocationResponse proto.InternalMessageInfo

func (m *LocationResponse) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *LocationResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type TimezoneRequest struct {
	Latlng               *LatLng  `protobuf:"bytes,1,opt,name=latlng,proto3" json:"latlng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimezoneRequest) Reset()         { *m = TimezoneRequest{} }
func (m *TimezoneRequest) String() string { return proto.CompactTextString(m) }
func (*TimezoneRequest) ProtoMessage()    {}
func (*TimezoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0eb003880ea8c15, []int{9}
}

func (m *TimezoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimezoneRequest.Unmarshal(m, b)
}
func (m *TimezoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimezoneRequest.Marshal(b, m, deterministic)
}
func (m *TimezoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimezoneRequest.Merge(m, src)
}
func (m *TimezoneRequest) XXX_Size() int {
	return xxx_messageInfo_TimezoneRequest.Size(m)
}
func (m *TimezoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TimezoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TimezoneRequest proto.InternalMessageInfo

func (m *TimezoneRequest) GetLatlng() *LatLng {
	if m != nil {
		return m.Latlng
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "geocoder.Location")
	proto.RegisterMapType((map[string]string)(nil), "geocoder.Location.ComponentsEntry")
	proto.RegisterType((*Bounds)(nil), "geocoder.Bounds")
	proto.RegisterType((*AdminLevel)(nil), "geocoder.AdminLevel")
	proto.RegisterType((*Country)(nil), "geocoder.Country")
	proto.RegisterType((*State)(nil), "geocoder.State")
	proto.RegisterType((*LatLng)(nil), "geocoder.LatLng")
	proto.RegisterType((*Timezone)(nil), "geocoder.Timezone")
	proto.RegisterType((*LocationRequest)(nil), "geocoder.LocationRequest")
	proto.RegisterMapType((map[string]string)(nil), "geocoder.LocationRequest.QueryEntry")
	proto.RegisterType((*LocationResponse)(nil), "geocoder.LocationResponse")
	proto.RegisterType((*TimezoneRequest)(nil), "geocoder.TimezoneRequest")
}

func init() { proto.RegisterFile("geocoder.proto", fileDescriptor_f0eb003880ea8c15) }

var fileDescriptor_f0eb003880ea8c15 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xed, 0x6a, 0x1b, 0x39,
	0x14, 0x65, 0xec, 0xf8, 0xeb, 0x3a, 0x89, 0x1d, 0x91, 0x2c, 0x5a, 0xff, 0xd8, 0x35, 0xb3, 0x5b,
	0x30, 0xa4, 0xb8, 0xad, 0xfb, 0x23, 0x21, 0xa5, 0xd0, 0x24, 0x84, 0x42, 0x30, 0x85, 0x4e, 0x0a,
	0xfd, 0x13, 0x30, 0xb2, 0xe7, 0xd6, 0x19, 0x32, 0x23, 0x39, 0x92, 0xc6, 0xd4, 0x7d, 0x82, 0x3e,
	0x5b, 0x5f, 0xa4, 0xaf, 0x51, 0x24, 0xcd, 0x87, 0x9b, 0xb8, 0xa1, 0xfd, 0xa7, 0x7b, 0xce, 0xb9,
	0x57, 0x57, 0xc7, 0x67, 0x30, 0xec, 0xce, 0x51, 0xcc, 0x44, 0x88, 0x72, 0xb8, 0x90, 0x42, 0x0b,
	0xd2, 0xcc, 0x6b, 0xff, 0x6b, 0x0d, 0x9a, 0x63, 0x31, 0x63, 0x3a, 0x12, 0x9c, 0xf4, 0xa0, 0xb9,
	0x90, 0x62, 0x19, 0x85, 0x28, 0xa9, 0xd7, 0xf7, 0x06, 0xad, 0xa0, 0xa8, 0xc9, 0x21, 0xec, 0x7d,
	0x12, 0x32, 0x61, 0x5a, 0x63, 0x38, 0x61, 0x61, 0x28, 0x51, 0x29, 0x5a, 0xb1, 0xa2, 0x6e, 0x41,
	0x9c, 0x3a, 0x9c, 0xfc, 0x07, 0x3b, 0x4a, 0x4b, 0x44, 0x3d, 0xe1, 0x69, 0x32, 0x45, 0x49, 0xb7,
	0xac, 0x70, 0xdb, 0x81, 0xef, 0x2c, 0x46, 0xfe, 0x85, 0x76, 0x2e, 0x62, 0x09, 0xd2, 0x9a, 0x95,
	0x40, 0x26, 0x61, 0x09, 0x9a, 0x75, 0x62, 0x31, 0x63, 0x71, 0xa4, 0x57, 0xb4, 0xee, 0xd6, 0xc9,
	0x6b, 0xd2, 0x87, 0xb6, 0x4a, 0xa7, 0x05, 0xdd, 0xb0, 0xf4, 0x3a, 0x64, 0xba, 0x75, 0x94, 0xe0,
	0x17, 0xc1, 0x91, 0x36, 0x5d, 0x77, 0x5e, 0x9b, 0xab, 0x17, 0x42, 0x69, 0x16, 0x4f, 0x8c, 0x0b,
	0xb4, 0xe5, 0xae, 0x76, 0xd0, 0xb9, 0x08, 0x91, 0xec, 0x42, 0x25, 0x0a, 0xe9, 0xbe, 0xc5, 0x2b,
	0x51, 0x48, 0x0e, 0xa1, 0x31, 0x13, 0x29, 0xd7, 0x72, 0x45, 0xab, 0x7d, 0x6f, 0xd0, 0x1e, 0xed,
	0x0d, 0x0b, 0x4b, 0xcf, 0x1d, 0x11, 0xe4, 0x0a, 0xf2, 0x04, 0x6a, 0x4a, 0x33, 0x8d, 0x74, 0xdb,
	0x4a, 0x3b, 0xa5, 0xf4, 0xca, 0xc0, 0x81, 0x63, 0xc9, 0x00, 0xea, 0x31, 0xd3, 0x63, 0x3e, 0xa7,
	0x60, 0x75, 0xdd, 0x52, 0x37, 0xb6, 0x78, 0x90, 0xf1, 0x46, 0x39, 0x15, 0x29, 0x0f, 0x15, 0xdd,
	0xb9, 0xaf, 0x3c, 0xb3, 0x78, 0x90, 0xf1, 0xe4, 0x08, 0xb6, 0x59, 0x98, 0x44, 0x7c, 0x12, 0xe3,
	0x12, 0x63, 0x45, 0xdb, 0xfd, 0xea, 0xa0, 0x3d, 0xda, 0x2f, 0xf5, 0xa7, 0x86, 0x1d, 0x1b, 0x32,
	0x68, 0xb3, 0xe2, 0xac, 0xc8, 0x19, 0xc0, 0x4c, 0x24, 0x0b, 0xc1, 0x91, 0x6b, 0x45, 0x0f, 0x6c,
	0x9b, 0xbf, 0xb6, 0x50, 0x16, 0x91, 0xe1, 0x79, 0x21, 0xba, 0xb0, 0x8f, 0x5e, 0xeb, 0xea, 0xbd,
	0x86, 0xce, 0x3d, 0x9a, 0x74, 0xa1, 0x7a, 0x8b, 0xab, 0x2c, 0x4c, 0xe6, 0x48, 0xf6, 0xa1, 0xb6,
	0x64, 0x71, 0x8a, 0x59, 0x76, 0x5c, 0x71, 0x52, 0x39, 0xf6, 0xfc, 0x1b, 0xa8, 0xbb, 0xd7, 0x90,
	0x21, 0xb4, 0xb8, 0x90, 0xfa, 0xe6, 0x82, 0x29, 0x6d, 0x7b, 0x37, 0x99, 0x53, 0x4a, 0x8c, 0x5e,
	0x89, 0x54, 0xdf, 0x7c, 0x44, 0xa5, 0xed, 0xdc, 0x8d, 0xfa, 0x42, 0xe2, 0x5f, 0x02, 0x94, 0x3e,
	0x98, 0x8d, 0xac, 0x5b, 0xf6, 0xa6, 0x5a, 0xe0, 0x0a, 0x42, 0x60, 0xcb, 0xc6, 0xd2, 0xad, 0x69,
	0xcf, 0x06, 0xb3, 0x79, 0xa9, 0x3a, 0xcc, 0x9c, 0xfd, 0x17, 0xd0, 0xc8, 0x02, 0x50, 0xb4, 0x78,
	0x1b, 0x5a, 0x2a, 0x6b, 0x2d, 0xcf, 0xa0, 0x66, 0x83, 0xf0, 0xdb, 0x0d, 0x4f, 0xa1, 0xee, 0x1e,
	0x61, 0xfc, 0x8c, 0x99, 0xf3, 0xc4, 0x0b, 0xcc, 0xd1, 0x22, 0x7c, 0x6e, 0xe5, 0x06, 0xe1, 0x73,
	0xff, 0x1f, 0x68, 0x7e, 0xc8, 0x83, 0x9e, 0x4f, 0xf3, 0xd6, 0xa6, 0x7d, 0xf7, 0xa0, 0x93, 0xff,
	0x9e, 0x01, 0xde, 0xa5, 0xa8, 0xf4, 0xa3, 0x5f, 0x3e, 0x85, 0xc6, 0xcf, 0xdf, 0x7b, 0x5e, 0x66,
	0x09, 0x36, 0xd7, 0x57, 0x1f, 0x49, 0x70, 0xcc, 0xe7, 0xe4, 0x04, 0x6a, 0x77, 0x29, 0xca, 0x15,
	0xdd, 0xb2, 0xc9, 0xfa, 0xff, 0x61, 0xb2, 0xb2, 0x4d, 0x86, 0xef, 0x8d, 0xcc, 0x65, 0xcb, 0xb5,
	0xf4, 0x8e, 0x01, 0x4a, 0xf0, 0x8f, 0x12, 0x75, 0x0d, 0xdd, 0x72, 0xbc, 0x5a, 0x08, 0xae, 0x90,
	0x3c, 0x87, 0x56, 0x9c, 0x61, 0x8a, 0x7a, 0x76, 0x1b, 0xb2, 0x61, 0x9b, 0x52, 0x44, 0xfe, 0x82,
	0x3a, 0x7e, 0x8e, 0x94, 0x76, 0xcf, 0x6f, 0x06, 0x59, 0xe5, 0xbf, 0x82, 0x4e, 0xee, 0x73, 0x6e,
	0x63, 0x69, 0x88, 0xf7, 0xb8, 0x21, 0xa3, 0x00, 0x76, 0xdf, 0x3a, 0xea, 0x0a, 0xe5, 0x32, 0x9a,
	0x21, 0x79, 0x03, 0x8d, 0x0c, 0x21, 0x7f, 0xff, 0xd2, 0x9e, 0x5e, 0x6f, 0x13, 0xe5, 0x9e, 0x36,
	0xba, 0x2c, 0x17, 0xca, 0x87, 0x1e, 0x41, 0x7d, 0x2c, 0xc4, 0x6d, 0xba, 0x58, 0x9f, 0x79, 0x6f,
	0xeb, 0x1e, 0x79, 0x48, 0x9d, 0x1d, 0x7c, 0xab, 0x90, 0x00, 0xb9, 0x9e, 0xa2, 0x94, 0xab, 0xeb,
	0x6c, 0x31, 0x39, 0xad, 0xdb, 0xff, 0x8f, 0x97, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x19, 0xfe,
	0x95, 0x91, 0x51, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GeocodeServiceClient is the client API for GeocodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeocodeServiceClient interface {
	Geocode(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationResponse, error)
}

type geocodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewGeocodeServiceClient(cc *grpc.ClientConn) GeocodeServiceClient {
	return &geocodeServiceClient{cc}
}

func (c *geocodeServiceClient) Geocode(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationResponse, error) {
	out := new(LocationResponse)
	err := c.cc.Invoke(ctx, "/geocoder.GeocodeService/Geocode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeocodeServiceServer is the server API for GeocodeService service.
type GeocodeServiceServer interface {
	Geocode(context.Context, *LocationRequest) (*LocationResponse, error)
}

// UnimplementedGeocodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGeocodeServiceServer struct {
}

func (*UnimplementedGeocodeServiceServer) Geocode(ctx context.Context, req *LocationRequest) (*LocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Geocode not implemented")
}

func RegisterGeocodeServiceServer(s *grpc.Server, srv GeocodeServiceServer) {
	s.RegisterService(&_GeocodeService_serviceDesc, srv)
}

func _GeocodeService_Geocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocodeServiceServer).Geocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geocoder.GeocodeService/Geocode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocodeServiceServer).Geocode(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GeocodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "geocoder.GeocodeService",
	HandlerType: (*GeocodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Geocode",
			Handler:    _GeocodeService_Geocode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geocoder.proto",
}

// TimezoneServiceClient is the client API for TimezoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimezoneServiceClient interface {
	Lookup(ctx context.Context, in *TimezoneRequest, opts ...grpc.CallOption) (*Timezone, error)
}

type timezoneServiceClient struct {
	cc *grpc.ClientConn
}

func NewTimezoneServiceClient(cc *grpc.ClientConn) TimezoneServiceClient {
	return &timezoneServiceClient{cc}
}

func (c *timezoneServiceClient) Lookup(ctx context.Context, in *TimezoneRequest, opts ...grpc.CallOption) (*Timezone, error) {
	out := new(Timezone)
	err := c.cc.Invoke(ctx, "/geocoder.TimezoneService/Lookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimezoneServiceServer is the server API for TimezoneService service.
type TimezoneServiceServer interface {
	Lookup(context.Context, *TimezoneRequest) (*Timezone, error)
}

// UnimplementedTimezoneServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTimezoneServiceServer struct {
}

func (*UnimplementedTimezoneServiceServer) Lookup(ctx context.Context, req *TimezoneRequest) (*Timezone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}

func RegisterTimezoneServiceServer(s *grpc.Server, srv TimezoneServiceServer) {
	s.RegisterService(&_TimezoneService_serviceDesc, srv)
}

func _TimezoneService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimezoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimezoneServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geocoder.TimezoneService/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimezoneServiceServer).Lookup(ctx, req.(*TimezoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TimezoneService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "geocoder.TimezoneService",
	HandlerType: (*TimezoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lookup",
			Handler:    _TimezoneService_Lookup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geocoder.proto",
}
