<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geocoder.proto

namespace Rentberry\Geocoder;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Location</code>
 */
class Location extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string provider = 1;</code>
     */
    protected $provider = '';
    /**
     * Generated from protobuf field <code>string formatted_address = 2;</code>
     */
    protected $formatted_address = '';
    /**
     * Generated from protobuf field <code>string street_number = 4;</code>
     */
    protected $street_number = '';
    /**
     * Generated from protobuf field <code>string street_name = 5;</code>
     */
    protected $street_name = '';
    /**
     * Generated from protobuf field <code>string locality = 6;</code>
     */
    protected $locality = '';
    /**
     * Generated from protobuf field <code>string sublocality = 7;</code>
     */
    protected $sublocality = '';
    /**
     * Generated from protobuf field <code>string timezone = 8;</code>
     */
    protected $timezone = '';
    /**
     * Generated from protobuf field <code>string postal_code = 9;</code>
     */
    protected $postal_code = '';
    /**
     * Generated from protobuf field <code>string id = 20;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.Country country = 3;</code>
     */
    protected $country = null;
    /**
     * Generated from protobuf field <code>.State state = 12;</code>
     */
    protected $state = null;
    /**
     * Generated from protobuf field <code>.LatLng latLng = 10;</code>
     */
    protected $latLng = null;
    /**
     * Generated from protobuf field <code>.Bounds bounds = 13;</code>
     */
    protected $bounds = null;
    /**
     * Generated from protobuf field <code>repeated .AdminLevel admin_levels = 11;</code>
     */
    private $admin_levels;
    /**
     * Generated from protobuf field <code>map<string, string> components = 21;</code>
     */
    private $components;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $provider
     *     @type string $formatted_address
     *     @type string $street_number
     *     @type string $street_name
     *     @type string $locality
     *     @type string $sublocality
     *     @type string $timezone
     *     @type string $postal_code
     *     @type string $id
     *     @type \Rentberry\Geocoder\Country $country
     *     @type \Rentberry\Geocoder\State $state
     *     @type \Rentberry\Geocoder\LatLng $latLng
     *     @type \Rentberry\Geocoder\Bounds $bounds
     *     @type \Rentberry\Geocoder\AdminLevel[]|\Google\Protobuf\Internal\RepeatedField $admin_levels
     *     @type array|\Google\Protobuf\Internal\MapField $components
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Geocoder::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string provider = 1;</code>
     * @return string
     */
    public function getProvider()
    {
        return $this->provider;
    }

    /**
     * Generated from protobuf field <code>string provider = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProvider($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string formatted_address = 2;</code>
     * @return string
     */
    public function getFormattedAddress()
    {
        return $this->formatted_address;
    }

    /**
     * Generated from protobuf field <code>string formatted_address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFormattedAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->formatted_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string street_number = 4;</code>
     * @return string
     */
    public function getStreetNumber()
    {
        return $this->street_number;
    }

    /**
     * Generated from protobuf field <code>string street_number = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStreetNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->street_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string street_name = 5;</code>
     * @return string
     */
    public function getStreetName()
    {
        return $this->street_name;
    }

    /**
     * Generated from protobuf field <code>string street_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStreetName($var)
    {
        GPBUtil::checkString($var, True);
        $this->street_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string locality = 6;</code>
     * @return string
     */
    public function getLocality()
    {
        return $this->locality;
    }

    /**
     * Generated from protobuf field <code>string locality = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setLocality($var)
    {
        GPBUtil::checkString($var, True);
        $this->locality = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sublocality = 7;</code>
     * @return string
     */
    public function getSublocality()
    {
        return $this->sublocality;
    }

    /**
     * Generated from protobuf field <code>string sublocality = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSublocality($var)
    {
        GPBUtil::checkString($var, True);
        $this->sublocality = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timezone = 8;</code>
     * @return string
     */
    public function getTimezone()
    {
        return $this->timezone;
    }

    /**
     * Generated from protobuf field <code>string timezone = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTimezone($var)
    {
        GPBUtil::checkString($var, True);
        $this->timezone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string postal_code = 9;</code>
     * @return string
     */
    public function getPostalCode()
    {
        return $this->postal_code;
    }

    /**
     * Generated from protobuf field <code>string postal_code = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPostalCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->postal_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 20;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Country country = 3;</code>
     * @return \Rentberry\Geocoder\Country
     */
    public function getCountry()
    {
        return isset($this->country) ? $this->country : null;
    }

    public function hasCountry()
    {
        return isset($this->country);
    }

    public function clearCountry()
    {
        unset($this->country);
    }

    /**
     * Generated from protobuf field <code>.Country country = 3;</code>
     * @param \Rentberry\Geocoder\Country $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkMessage($var, \Rentberry\Geocoder\Country::class);
        $this->country = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.State state = 12;</code>
     * @return \Rentberry\Geocoder\State
     */
    public function getState()
    {
        return isset($this->state) ? $this->state : null;
    }

    public function hasState()
    {
        return isset($this->state);
    }

    public function clearState()
    {
        unset($this->state);
    }

    /**
     * Generated from protobuf field <code>.State state = 12;</code>
     * @param \Rentberry\Geocoder\State $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkMessage($var, \Rentberry\Geocoder\State::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.LatLng latLng = 10;</code>
     * @return \Rentberry\Geocoder\LatLng
     */
    public function getLatLng()
    {
        return isset($this->latLng) ? $this->latLng : null;
    }

    public function hasLatLng()
    {
        return isset($this->latLng);
    }

    public function clearLatLng()
    {
        unset($this->latLng);
    }

    /**
     * Generated from protobuf field <code>.LatLng latLng = 10;</code>
     * @param \Rentberry\Geocoder\LatLng $var
     * @return $this
     */
    public function setLatLng($var)
    {
        GPBUtil::checkMessage($var, \Rentberry\Geocoder\LatLng::class);
        $this->latLng = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Bounds bounds = 13;</code>
     * @return \Rentberry\Geocoder\Bounds
     */
    public function getBounds()
    {
        return isset($this->bounds) ? $this->bounds : null;
    }

    public function hasBounds()
    {
        return isset($this->bounds);
    }

    public function clearBounds()
    {
        unset($this->bounds);
    }

    /**
     * Generated from protobuf field <code>.Bounds bounds = 13;</code>
     * @param \Rentberry\Geocoder\Bounds $var
     * @return $this
     */
    public function setBounds($var)
    {
        GPBUtil::checkMessage($var, \Rentberry\Geocoder\Bounds::class);
        $this->bounds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .AdminLevel admin_levels = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdminLevels()
    {
        return $this->admin_levels;
    }

    /**
     * Generated from protobuf field <code>repeated .AdminLevel admin_levels = 11;</code>
     * @param \Rentberry\Geocoder\AdminLevel[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdminLevels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rentberry\Geocoder\AdminLevel::class);
        $this->admin_levels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> components = 21;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getComponents()
    {
        return $this->components;
    }

    /**
     * Generated from protobuf field <code>map<string, string> components = 21;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setComponents($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->components = $arr;

        return $this;
    }

}

