<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geocoder.proto

namespace Rentberry\Geocoder;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TimezoneRequest</code>
 */
class TimezoneRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.LatLng latlng = 1;</code>
     */
    protected $latlng = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rentberry\Geocoder\LatLng $latlng
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Geocoder::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.LatLng latlng = 1;</code>
     * @return \Rentberry\Geocoder\LatLng
     */
    public function getLatlng()
    {
        return isset($this->latlng) ? $this->latlng : null;
    }

    public function hasLatlng()
    {
        return isset($this->latlng);
    }

    public function clearLatlng()
    {
        unset($this->latlng);
    }

    /**
     * Generated from protobuf field <code>.LatLng latlng = 1;</code>
     * @param \Rentberry\Geocoder\LatLng $var
     * @return $this
     */
    public function setLatlng($var)
    {
        GPBUtil::checkMessage($var, \Rentberry\Geocoder\LatLng::class);
        $this->latlng = $var;

        return $this;
    }

}

